from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from authentication.views import RegisterView,AdminRegistrationView,UserLoginView,AdminLoginView,ProtectedView,MailboxView,DeleteMailboxView,Userlist,UserDetailsWithMailboxView,UpdateMailboxPriceView,GlobalAddressView,AddressBookView,SetDefaultAddressView,UserAddressListForAdminView,PasswordResetRequestView,PasswordResetConfirmView,ChangePasswordView,PayPalCheckoutView,PayPalExecutePaymentView,MailboxCheckoutDataView,GenerateUsername,AdminDeleteUserView,SuspiciousUserList,BlockedIPList,BannerUploadView,BannerListView,BannerDeleteView,SetActiveBannerView,AdminBannerList,AdminUpdateShipmentStatusView,AdminUserShipmentListView,ShippingCostByWeightView,BrandLogoUploadView, BrandLogoListView, AdminBrandLogoList, BrandLogoDeleteView, SetActiveBrandLogoView
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("admin/register/", AdminRegistrationView.as_view(), name="admin-register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("admin/login/", AdminLoginView.as_view(), name="admin-login"),
    path("refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("protected/", ProtectedView.as_view(), name="protected"),
    path("mailbox/<int:user_id>/", MailboxView.as_view(), name="mailbox-list"),
    path("mailbox/create/", MailboxView.as_view(), name="mailbox-create"),
    path("mailbox/delete/<int:pk>/", DeleteMailboxView.as_view(), name="mailbox-delete"),
    path("user_list/", Userlist.as_view(), name="user_list"),
    path("user-details/<int:pk>/", UserDetailsWithMailboxView.as_view(), name="user-details"),
    path("mailbox/update-price/<int:pk>/", UpdateMailboxPriceView.as_view(), name="update-mailbox-price"),
    path("global-address/", GlobalAddressView.as_view(), name="global-address-list"),
    path("global-address/<int:pk>/", GlobalAddressView.as_view(), name="global-address-detail"),
    path("addressbook/", AddressBookView.as_view(), name="address-book"),
    path("addressbook/set-default/<int:pk>/", SetDefaultAddressView.as_view(), name="set-default-address"),
    path("admin/user/<int:user_id>/addresses/", UserAddressListForAdminView.as_view(), name="admin-user-addresses"),
    path("password-reset/", PasswordResetRequestView.as_view(), name="password-reset-request"),
    path("password-reset-confirm/<uidb64>/<token>/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("paypal/checkout/", PayPalCheckoutView.as_view(), name="paypal-checkout"),
    path("paypal/execute/", PayPalExecutePaymentView.as_view(), name="paypal-execute"),
    path("mailbox/checkout-data/", MailboxCheckoutDataView.as_view(), name="mailbox-checkout-data"),
    path("generate-username/", GenerateUsername.as_view(), name="generate-username"),
    path("admin/user/<int:user_id>/delete/", AdminDeleteUserView.as_view(), name="admin-user-delete"),
    path("admin/suspicious-users/", SuspiciousUserList.as_view(), name="suspicious-users"),
    path("admin/blocked-ips/<int:user_id>/", BlockedIPList.as_view(), name="blocked-ips"),
    path("admin/banner/upload/", BannerUploadView.as_view(), name="upload-banner"),
    path("banners/", BannerListView.as_view(), name="get-banners"),
    path("admin/banner/delete/<int:banner_id>/", BannerDeleteView.as_view(), name="delete-banner"),
    path("admin/banner/set-active/<int:banner_id>/", SetActiveBannerView.as_view(), name="set-active-banner"),
    path("admin/banners/", AdminBannerList.as_view(), name="all-banners"),
    path("admin/update-shipment-status/<int:shipment_id>/", AdminUpdateShipmentStatusView.as_view(), name="admin-user-shipments-update"),
    path("admin/user-shipments/<int:user_id>/", AdminUserShipmentListView.as_view(), name="admin-user-shipments"),
    path('shipping/price-by-weight/', ShippingCostByWeightView.as_view(), name='shipping-price-by-weight'),
    path("admin/brand-logo/upload/", BrandLogoUploadView.as_view(), name="upload-brand-logo"),
    path("brand-logos/", BrandLogoListView.as_view(), name="get-brand-logos"),
    path("admin/brand-logos/", AdminBrandLogoList.as_view(), name="all-brand-logos"),
    path("admin/brand-logo/delete/<int:logo_id>/", BrandLogoDeleteView.as_view(), name="delete-brand-logo"),
    path("admin/brand-logo/set-active/<int:logo_id>/", SetActiveBrandLogoView.as_view(), name="set-active-brand-logo"),
]